DROP TABLE IF EXISTS flags_group;
DROP TABLE IF EXISTS flags_group_state;
DROP TABLE IF EXISTS folder;
DROP TABLE IF EXISTS environment;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS organization;
DROP EXTENSION IF EXISTS "uuid-ossp";