DROP TABLE IF EXISTS project_members;
DROP TABLE IF EXISTS feature_flags;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS environments;
DROP TABLE IF EXISTS project_enviornments;
DROP TABLE IF EXISTS project_features;
DROP TABLE IF EXISTS feature_states;
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS feature_flag_type CASCADE;
