// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: environment.sql

package queries

import (
	"context"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments(name, color, id)
VALUES ($1, $2, $3)
RETURNING uuid, id, name, color, org_id, created_at
`

type CreateEnvironmentParams struct {
	Name  string  `json:"name"`
	Color *string `json:"color"`
	ID    *int32  `json:"-"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.Name, arg.Color, arg.ID)
	var i Environment
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.Name,
		&i.Color,
		&i.OrgID,
		&i.CreatedAt,
	)
	return i, err
}
