// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: flagsgroupstates.sql

package queries

import (
	"context"
)

const createFlagsGroupState = `-- name: CreateFlagsGroupState :one
INSERT INTO flags_group_states(flags_group_id)
VALUES ($1)
RETURNING uuid, id, flags_group_id, js, created_at
`

func (q *Queries) CreateFlagsGroupState(ctx context.Context, flagsGroupID *int32) (FlagsGroupState, error) {
	row := q.db.QueryRow(ctx, createFlagsGroupState, flagsGroupID)
	var i FlagsGroupState
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.FlagsGroupID,
		&i.Js,
		&i.CreatedAt,
	)
	return i, err
}

const getFlagsGroupState = `-- name: GetFlagsGroupState :one
SELECT uuid, id, flags_group_id, js, created_at
FROM flags_group_states
WHERE flags_group_id = $1
`

func (q *Queries) GetFlagsGroupState(ctx context.Context, flagsGroupID *int32) (FlagsGroupState, error) {
	row := q.db.QueryRow(ctx, getFlagsGroupState, flagsGroupID)
	var i FlagsGroupState
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.FlagsGroupID,
		&i.Js,
		&i.CreatedAt,
	)
	return i, err
}

const getFlagsGroupStateByUUID = `-- name: GetFlagsGroupStateByUUID :one
SELECT uuid, id, flags_group_id, js, created_at
FROM flags_group_states
WHERE uuid = $1
`

func (q *Queries) GetFlagsGroupStateByUUID(ctx context.Context, uuid string) (FlagsGroupState, error) {
	row := q.db.QueryRow(ctx, getFlagsGroupStateByUUID, uuid)
	var i FlagsGroupState
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.FlagsGroupID,
		&i.Js,
		&i.CreatedAt,
	)
	return i, err
}

const updateFlagGroupsStateJS = `-- name: UpdateFlagGroupsStateJS :one
UPDATE flags_group_states
SET js = $1
WHERE flags_group_id = $2
RETURNING uuid, id, flags_group_id, js, created_at
`

type UpdateFlagGroupsStateJSParams struct {
	Js           *string `json:"js"`
	FlagsGroupID *int32  `json:"-"`
}

func (q *Queries) UpdateFlagGroupsStateJS(ctx context.Context, arg UpdateFlagGroupsStateJSParams) (FlagsGroupState, error) {
	row := q.db.QueryRow(ctx, updateFlagGroupsStateJS, arg.Js, arg.FlagsGroupID)
	var i FlagsGroupState
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.FlagsGroupID,
		&i.Js,
		&i.CreatedAt,
	)
	return i, err
}
