// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type UserRole string

const (
	UserRoleMember UserRole = "member"
	UserRoleAdmin  UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type FeatureFlag struct {
	ID        int32
	ProjectID int64
	Type      int32
	Name      string
}

type Project struct {
	ID        int32
	Name      string
	OwnerID   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ProjectMember struct {
	UserID    int64
	ProjectID int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID            int32
	Name          string
	Password      string
	Email         string
	EmailVerified bool
	Role          UserRole
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
