// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: organization.sql

package queries

import (
	"context"
	"time"
)

const addOrganizationMember = `-- name: AddOrganizationMember :exec
INSERT INTO organization_members(user_id, org_id)
VALUES ($1, $2)
RETURNING user_id, org_id
`

type AddOrganizationMemberParams struct {
	UserID *int32 `json:"-"`
	OrgID  *int32 `json:"-"`
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) error {
	_, err := q.db.Exec(ctx, addOrganizationMember, arg.UserID, arg.OrgID)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations(name)
VALUES ($1)
RETURNING uuid, id, name, created_at
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var i Organization
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationByUUID = `-- name: GetOrganizationByUUID :one
SELECT uuid, id, name, created_at
FROM organizations
WHERE uuid = $1
`

func (q *Queries) GetOrganizationByUUID(ctx context.Context, uuid string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByUUID, uuid)
	var i Organization
	err := row.Scan(
		&i.Uuid,
		&i.ID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT o.uuid AS uuid,
    o.name AS name,
    o.created_at AS created_at
FROM users u
    JOIN organization_members om ON u.id = om.user_id
    JOIN organizations o ON om.org_id = o.id
WHERE u.uuid = $1
`

type GetUserOrganizationsRow struct {
	Uuid      string     `json:"uuid"`
	Name      string     `json:"name"`
	CreatedAt *time.Time `json:"created_at"`
}

func (q *Queries) GetUserOrganizations(ctx context.Context, uuid string) ([]GetUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrganizations, uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrganizationsRow
	for rows.Next() {
		var i GetUserOrganizationsRow
		if err := rows.Scan(&i.Uuid, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
