// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: project.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members(user_id, project_id)
VALUES ($1, $2)
`

type AddProjectMemberParams struct {
	UserID    int64 `json:"user_id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember, arg.UserID, arg.ProjectID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects(name, owner_id, org_id)
VALUES ($1, $2, $3)
RETURNING id, name, uuid, org_id, owner_id, created_at, updated_at
`

type CreateProjectParams struct {
	Name    string `json:"name"`
	OwnerID int64  `json:"owner_id"`
	OrgID   int64  `json:"org_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.OwnerID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uuid,
		&i.OrgID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, uuid, org_id, owner_id, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int32) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Uuid,
		&i.OrgID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOrgProjects = `-- name: GetUserOrgProjects :many
SELECT id,
    name,
    uuid,
    org_id
FROM projects p
WHERE p.org_id = $2
    AND EXISTS (
        SELECT user_id, org_id, created_at, updated_at
        FROM organization_members
        WHERE user_id = $1
            AND org_id = $2
    )
`

type GetUserOrgProjectsParams struct {
	UserID int64 `json:"user_id"`
	OrgID  int64 `json:"org_id"`
}

type GetUserOrgProjectsRow struct {
	ID    int32         `json:"id"`
	Name  string        `json:"name"`
	Uuid  uuid.NullUUID `json:"uuid"`
	OrgID int64         `json:"org_id"`
}

func (q *Queries) GetUserOrgProjects(ctx context.Context, arg GetUserOrgProjectsParams) ([]GetUserOrgProjectsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrgProjects, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrgProjectsRow
	for rows.Next() {
		var i GetUserOrgProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Uuid,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
