// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user.sql

package queries

import (
	"context"
)

const createActiveUser = `-- name: CreateActiveUser :one
INSERT INTO users (name, email, password, email_verified, active)
VALUES ($1, $2, $3, TRUE, TRUE)
RETURNING uuid, name, email, password, email_verified, active, created_at
`

type CreateActiveUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateActiveUser(ctx context.Context, arg CreateActiveUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createActiveUser, arg.Name, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.EmailVerified,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
